import {
  LucideIcon,
  // Ícones gerais e de utilidade já usados ou muito comuns
  AlertTriangle,
  Info,
  Package,
  PackageCheck,
  PackageX,
  DollarSign,
  User,
  LogOut,
  Settings,
  Home,
  Users,
  ClipboardList,
  BarChart,
  Calendar,
  Clock,
  MapPin,
  Phone,
  Mail,
  Globe,
  Link,
  ExternalLink,
  Image,
  Camera,
  Video,
  FileText,
  Folder,
  Book,
  Award,
  Gift,
  Heart,
  Star,
  Check,
  X,
  Edit,
  Trash,
  Plus,
  Minus,
  ShoppingCart,
  Search,
  ChevronLeft,
  ChevronRight,
  List,
  // Ícones relevantes para categorias de uma Bodega
  Beer,
  CupSoda,
  GlassWater,
  Wine,
  Coffee,
  Milk,
  Sparkles, // Para "Outros" ou "Especiais"
  UtensilsCrossed, // Para "Comida" ou "Snacks"
  Zap, // Para "Energéticos"
  PackagePlus, // Para "Kits" ou "Combos"
  Apple, // Frutas
  Lemon,
  Orange,
  Banana,
  Pizza, // Comidas
  Burger,
  Fries,
  Cookie,
  Cake,
  IceCream,
} from 'lucide-react';

// Mapeia nomes de string para componentes de ícone Lucide
export const lucideIconMap: { [key: string]: LucideIcon } = {
  AlertTriangle,
  Info,
  Package,
  PackageCheck,
  PackageX,
  DollarSign,
  User,
  LogOut,
  Settings,
  Home,
  Users,
  ClipboardList,
  BarChart,
  Calendar,
  Clock,
  MapPin,
  Phone,
  Mail,
  Globe,
  Link,
  ExternalLink,
  Image,
  Camera,
  Video,
  FileText,
  Folder,
  Book,
  Award,
  Gift,
  Heart,
  Star,
  Check,
  X,
  Edit,
  Trash,
  Plus,
  Minus,
  ShoppingCart,
  Search,
  ChevronLeft,
  ChevronRight,
  List,
  Beer,
  CupSoda,
  GlassWater,
  Wine,
  Coffee,
  Milk,
  Sparkles,
  UtensilsCrossed,
  Zap,
  PackagePlus,
  Apple,
  Lemon,
  Orange,
  Banana,
  Pizza,
  Burger,
  Fries,
  Cookie,
  Cake,
  IceCream,
};

// Função para obter um componente de ícone pelo nome
export const getLucideIcon = (iconName: string): LucideIcon | undefined => {
  return lucideIconMap[iconName];
};

// Lista de nomes de ícones disponíveis para seleção no formulário
export const availableIconNames: string[] = Object.keys(lucideIconMap).sort();